FORMAT: 1A

# Playground

## Post [/post/{id}]

### Detail view [GET]

- Response 200 (application/json)

    - Attributes (Post)

## Posts [/posts]

### List view [GET]

- Response 200 (application/json)

    - Attributes (array)
        - (Post)
        - (Post)
            - id: 2
            - title: `Different title`

# Data Structures

## Post (object)

- id: 1 (number)
- title: `Default title`
- content: `Lorem ipsum bla bla bla.`
- author (User)

## User (object)

- id: 10 (number)
- name: `John Doe`